spring:
  datasource:
    # druid 连接池
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/sqlonlinejudge?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 5
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatisConfig.xml
  type-aliases-package: cn.edu.jmu.sqlonlinejudge.entity

# MP配置
mybatis-plus:
  # 支持统配符 * 或者 ; 分割
  typeEnumsPackage: cn.edu.jmu.sqlonlinejudge.service.enums
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.extension.handlers.MybatisEnumTypeHandler
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: cn.edu.jmu.sqlonlinejudge.entity

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true

login-type:
  user: User
  admin: Admin
